[project]
name = "ai-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Afaq-Ejaz", email = "afaqthejaz@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.1.0",
    "fastapi>=0.141.1",
    "google-genai>=1.14.0",
    "numpy>=2.2.0",
    "pydantic>=2.13.5",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
ai-dev = "ai_dev:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
